# Organizations:
#     - &OrdererOrg
#         Name: OrdererOrg
#         ID: OrdererMSP
#         MSPDir: crypto-config/ordererOrganizations/hiam.hal/msp
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('OrdererMSP.member')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('OrdererMSP.member')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('OrdererMSP.admin')"

#     - &org0
#         Name: org0MSP
#         ID: org0MSP
#         MSPDir: crypto-config/peerOrganizations/org0.hiam.hal/msp
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('org0MSP.admin', 'org0MSP.peer', 'org0MSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('org0MSP.admin', 'org0MSP.client')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('org0MSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('org0MSP.peer')"
#         AnchorPeers:
#             - Host: peer0.org0.hiam.hal
#               Port: 17051
    
#     - &org1
#         Name: org1MSP
#         ID: org1MSP
#         MSPDir: crypto-config/peerOrganizations/org1.hiam.hal/msp
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('org1MSP.admin', 'org1MSP.peer', 'org1MSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('org1MSP.admin', 'org1MSP.client')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('org1MSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('org1MSP.peer')"
#         AnchorPeers:
#             - Host: peer0.org1.hiam.hal
#               Port: 7051

#     - &org2
#         Name: org2MSP
#         ID: org2MSP
#         MSPDir: crypto-config/peerOrganizations/org2.hiam.hal/msp
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('org2MSP.admin', 'org2MSP.peer', 'org2MSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('org2MSP.admin', 'org2MSP.client')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('org2MSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('org2MSP.peer')"    
#         AnchorPeers:
#             - Host: peer0.org2.hiam.hal
#               Port: 9051

#     - &org3
#         Name: org3MSP
#         ID: org3MSP
#         MSPDir: crypto-config/peerOrganizations/org3.hiam.hal/msp
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('org3MSP.admin', 'org3MSP.peer', 'org3MSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('org3MSP.admin', 'org3MSP.client')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('org3MSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('org3MSP.peer')"
#         AnchorPeers:
#             - Host: peer0.org3.hiam.hal
#               Port: 11051

#     - &org4
#         Name: org4MSP
#         ID: org4MSP
#         MSPDir: crypto-config/peerOrganizations/org4.hiam.hal/msp
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('org4MSP.admin', 'org4MSP.peer', 'org4MSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('org4MSP.admin', 'org4MSP.client')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('org4MSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('org4MSP.peer')"
#         AnchorPeers:
#             - Host: peer0.org4.hiam.hal
#               Port: 13051

#     - &org5
#         Name: org5MSP
#         ID: org5MSP
#         MSPDir: crypto-config/peerOrganizations/org5.hiam.hal/msp
#         Policies:
#             Readers:
#                 Type: Signature
#                 Rule: "OR('org5MSP.admin', 'org5MSP.peer', 'org5MSP.client')"
#             Writers:
#                 Type: Signature
#                 Rule: "OR('org5MSP.admin', 'org5MSP.client')"
#             Admins:
#                 Type: Signature
#                 Rule: "OR('org5MSP.admin')"
#             Endorsement:
#                 Type: Signature
#                 Rule: "OR('org5MSP.peer')"
#         AnchorPeers:
#             - Host: peer0.org5.hiam.hal
#               Port: 15051

# Capabilities:
#     Channel: &ChannelCapabilities
#         V2_0: true
#     Orderer: &OrdererCapabilities
#         V2_0: true
#     Application: &ApplicationCapabilities
#         V2_0: true

# Application: &ApplicationDefaults
#     Organizations:
#     Policies:
#         Readers:
#             Type: ImplicitMeta
#             Rule: "ANY Readers"
#         Writers:
#             Type: ImplicitMeta
#             Rule: "ANY Writers"
#         Admins:
#             Type: ImplicitMeta
#             Rule: "MAJORITY Admins"
#         LifecycleEndorsement:
#             Type: ImplicitMeta
#             Rule: "MAJORITY Endorsement"
#         Endorsement:
#             Type: ImplicitMeta
#             Rule: "MAJORITY Endorsement"

#     Capabilities:
#         <<: *ApplicationCapabilities

# Orderer: &OrdererDefaults
#     OrdererType: etcdraft
#     EtcdRaft:
#         Consenters:
#         - Host: orderer1.hiam.hal
#           Port: 7050
#           ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
#           ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
#     Addresses:
#         - orderer1.hiam.hal:7050
#     BatchTimeout: 2s
#     BatchSize:
#         MaxMessageCount: 10
#         AbsoluteMaxBytes: 99 MB
#         PreferredMaxBytes: 512 KB
#     Organizations:
#     Policies:
#         Readers:
#             Type: ImplicitMeta
#             Rule: "ANY Readers"
#         Writers:
#             Type: ImplicitMeta
#             Rule: "ANY Writers"
#         Admins:
#             Type: ImplicitMeta
#             Rule: "MAJORITY Admins"
#         BlockValidation:
#             Type: ImplicitMeta
#             Rule: "ANY Writers"

# Channel: &ChannelDefaults
#     Policies:
#         Readers:
#             Type: ImplicitMeta
#             Rule: "ANY Readers"
#         Writers:
#             Type: ImplicitMeta
#             Rule: "ANY Writers"
#         Admins:
#             Type: ImplicitMeta
#             Rule: "MAJORITY Admins"
#     Capabilities:
#         <<: *ChannelCapabilities

# Profiles:

#     BasicChannel:
#         Consortium: SampleConsortium
#         <<: *ChannelDefaults
#         Application:
#             <<: *ApplicationDefaults
#             Organizations:
#                 - *org0
#                 - *org1
#                 - *org2
#                 - *org3
#                 - *org4
#                 - *org5
#             Capabilities:
#                 <<: *ApplicationCapabilities

#     OrdererGenesis:
#         <<: *ChannelDefaults
#         Capabilities:
#             <<: *ChannelCapabilities
#         Orderer:
#             <<: *OrdererDefaults
#             OrdererType: etcdraft
#             EtcdRaft:
#                 Consenters:
#                 - Host: orderer1.hiam.hal
#                   Port: 7050
#                   ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
#                   ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
#                 - Host: orderer2.hiam.hal
#                   Port: 8050
#                   ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer2.hiam.hal/tls/server.crt
#                   ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer2.hiam.hal/tls/server.crt
#                 - Host: orderer3.hiam.hal
#                   Port: 9050
#                   ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer3.hiam.hal/tls/server.crt
#                   ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer3.hiam.hal/tls/server.crt
#             Addresses:
#                 - orderer1.hiam.hal:7050
#                 - orderer2.hiam.hal:8050
#                 - orderer3.hiam.hal:9050

#             Organizations:
#             - *OrdererOrg
#             Capabilities:
#                 <<: *OrdererCapabilities
#         Consortiums:
#             SampleConsortium:
#                 Organizations:
#                 - *org0
#                 - *org1
#                 - *org2
#                 - *org3
#                 - *org4
#                 - *org5
                
#     channel1:
#         Consortium: SampleConsortium
#         <<: *ChannelDefaults
#         Application:
#             <<: *ApplicationDefaults
#             Organizations:
#                 - *org0
#                 - *org1
#                 - *org2
#                 - *org3
#                 - *org4
#                 - *org5
#             Capabilities:
#                 <<: *ApplicationCapabilities

#     channel2:
#         Consortium: SampleConsortium
#         <<: *ChannelDefaults
#         Application:
#             <<: *ApplicationDefaults
#             Organizations:
#                 - *org0
#                 - *org2
#                 - *org3
#                 - *org5
#             Capabilities:
#                 <<: *ApplicationCapabilities

Organizations:
    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/hiam.hal/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &org0
        Name: org0MSP
        ID: org0MSP
        MSPDir: crypto-config/peerOrganizations/org0.hiam.hal/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org0MSP.admin', 'org0MSP.peer', 'org0MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('org0MSP.admin', 'org0MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('org0MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('org0MSP.peer')"
        AnchorPeers:
            - Host: peer0.org0.hiam.hal
              Port: 17051
    
    - &org1
        Name: org1MSP
        ID: org1MSP
        MSPDir: crypto-config/peerOrganizations/org1.hiam.hal/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org1MSP.admin', 'org1MSP.peer', 'org1MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('org1MSP.admin', 'org1MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('org1MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('org1MSP.peer')"
        AnchorPeers:
            - Host: peer0.org1.hiam.hal
              Port: 7051

    - &org2
        Name: org2MSP
        ID: org2MSP
        MSPDir: crypto-config/peerOrganizations/org2.hiam.hal/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org2MSP.admin', 'org2MSP.peer', 'org2MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('org2MSP.admin', 'org2MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('org2MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('org2MSP.peer')"    
        AnchorPeers:
            - Host: peer0.org2.hiam.hal
              Port: 9051

    - &org3
        Name: org3MSP
        ID: org3MSP
        MSPDir: crypto-config/peerOrganizations/org3.hiam.hal/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org3MSP.admin', 'org3MSP.peer', 'org3MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('org3MSP.admin', 'org3MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('org3MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('org3MSP.peer')"
        AnchorPeers:
            - Host: peer0.org3.hiam.hal
              Port: 11051

    - &org4
        Name: org4MSP
        ID: org4MSP
        MSPDir: crypto-config/peerOrganizations/org4.hiam.hal/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org4MSP.admin', 'org4MSP.peer', 'org4MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('org4MSP.admin', 'org4MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('org4MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('org4MSP.peer')"
        AnchorPeers:
            - Host: peer0.org4.hiam.hal
              Port: 13051

    - &org5
        Name: org5MSP
        ID: org5MSP
        MSPDir: crypto-config/peerOrganizations/org5.hiam.hal/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org5MSP.admin', 'org5MSP.peer', 'org5MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('org5MSP.admin', 'org5MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('org5MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('org5MSP.peer')"
        AnchorPeers:
            - Host: peer0.org5.hiam.hal
              Port: 15051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
        - Host: orderer1.hiam.hal
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
        - Host: orderer2.hiam.hal
          Port: 8050
          ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer2.hiam.hal/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer2.hiam.hal/tls/server.crt
        - Host: orderer3.hiam.hal
          Port: 9050
          ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer3.hiam.hal/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer3.hiam.hal/tls/server.crt
    Addresses:
        - orderer1.hiam.hal:7050
        - orderer2.hiam.hal:8050
        - orderer3.hiam.hal:9050

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    BasicChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *org0
                - *org1
                - *org2
                - *org3
                - *org4
                - *org5
            Capabilities:
                <<: *ApplicationCapabilities

    OrdererGenesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer1.hiam.hal
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer1.hiam.hal/tls/server.crt
                - Host: orderer2.hiam.hal
                  Port: 8050
                  ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer2.hiam.hal/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer2.hiam.hal/tls/server.crt
                - Host: orderer3.hiam.hal
                  Port: 9050
                  ClientTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer3.hiam.hal/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/hiam.hal/orderers/orderer3.hiam.hal/tls/server.crt
            Addresses:
                - orderer1.hiam.hal:7050
                - orderer2.hiam.hal:8050
                - orderer3.hiam.hal:9050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                - *org0
                - *org1
                - *org2
                - *org3
                - *org4
                - *org5
                
    channel1:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *org0
                - *org1
                - *org2
                - *org3
                - *org4
                - *org5
            Capabilities:
                <<: *ApplicationCapabilities

    channel2:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *org0
                - *org2
                - *org3
                - *org5
            Capabilities:
                <<: *ApplicationCapabilities
