OrdererOrgs:
  - Name: Orderer
    Domain: hiam.hal
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer2
        SANS:
          - "localhost"
          - "127.0.0.1"
      - Hostname: orderer3
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:
  - Name: org0   
    Domain: org0.hiam.hal
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org1  
    Domain: org1.hiam.hal
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org2  
    Domain: org2.hiam.hal
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org3  
    Domain: org3.hiam.hal
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org4  
    Domain: org4.hiam.hal
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: org5  
    Domain: org5.hiam.hal
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
